### PR TITLE
DO NOT MERGE: Beats dissect compatibility suite

### PR DESCRIPTION
**Pull request by ph**
DO NOT MERGE:

This is an attempt to run unified tests for the dissect syntax. The
JSON fixtures is extracted from the beats table based suite.

### CODE REVIEW

**Comment by ph** [comment]
@guyboertje Another thing which I would like some clarification, I understand that tokenizer is defined from left to right, but what happens if the delimiter is not at the beginning of the string.

take this case
```yaml
tokenizer: "MACHINE[%{key}]%{rest}"
message: "18-Apr-2018 06:53:20.411 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header\n Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.\n java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens\n    at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:426)\n    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)\n    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)\n    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)\n    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n    at java.lang.Thread.run(Thread.java:748) MACHINE[hello]"
```

The `machine` delimiter exists but it is present at the end of the string when you run the test, I would have expected it to capture `hello`, but as you see, it captures anything but `hello`.
```
  expected: "hello"
            got: "018 06:53:20.411 INFO [http-nio-8080-exec-1"
```

Adding a `skip field` before `MACHINE` fix the problem and correctly capture `hello`.

So what is the expected behavior here? I see two possible solutions:

- Force *#indexof* of the first delimiter to match the beginning of the string.
- Allow *#indexof* to look ahead and ignore the beginning of the string.

**Comment by guyboertje** [comment]
Regarding your first comment on the unexpected behaviour, see [this issue](https://github.com/logstash-plugins/logstash-filter-dissect/issues/22). I know we discussed this face to face. I make this comment for other readers.

**Comment by guyboertje** [comment]
Regarding [the second comment](https://github.com/logstash-plugins/logstash-filter-dissect/pull/55#issuecomment-384019165), this is by design.
A dissection of `MACHINE[%{key}]%{rest}` is explicitly saying that the field value will start with `MACHINE[`.
If one had two values:
`MACHINE[foo]`
`bar MACHINE[foo]`
then you must make allowances for it. The skip field will capture 0 or more characters before the first delimiter `MACHINE[`

That said, the question is really whether a dissection is like an anchored regex or not `/^MACHINE[(\w+)]/` vs /MACHINE[(\w+)]/` and would changing it be a breaking change?

**Comment by ph** [comment]
@guyboertje Well, I believe making it anchored would be more explicit.

I do understand adding a skip field at the beginning to deal is similar to using `(.*)` in a regular expression, which more or less act as a glob/wildcard. But still, without the presence of the skip field I do not understand why `018 06:53:20.411 INFO [http-nio-8080-exec-1` was extracted, where is `April` also why we have `018` at the beginning, it should be `18`. 

The beginning of the original string look like this:
```
18-Apr-2018 06:53:20.411 INFO [http-nio-8080-exec-1]
```

**Comment by ph** [comment]
Adding the rspec error to the discussion:
```
  1) LogStash::Filters::Dissect Beats compatibility suite Extract at the end of string should dissect properly
     Failure/Error: expect(event.get(k)).to eq(v)

       expected: "hello"
            got: "018 06:53:20.411 INFO [http-nio-8080-exec-1"

       (compared using ==)
     # ./spec/filters/dissect_spec.rb:346:in `block in (root)'
     # ./spec/filters/dissect_spec.rb:345:in `block in (root)'

```
Data:
```json
	{
		"name": "Extract at the end of string",
		"tok": "MACHINE[%{key}]%{rest}",
		"msg": "18-Apr-2018 06:53:20.411 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header\n Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.\n java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens\n    at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:426)\n    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)\n    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)\n    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)\n    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n    at java.lang.Thread.run(Thread.java:748) MACHINE[hello]",
		"expected": {
			"key": "hello",
			"rest": ""
		},
		"skip": false
	},
```
```

**Comment by ph** [comment]
@guyboertje I though that delimiter needed to be present for a key to be correctly captured.

**Comment by guyboertje** [comment]
> The skipped beginning is the same length as MACHINE[, so this make me think something is wrong with the algo

Yes, that is my conclusion too I will add that one as a Java test and debug.

**Comment by ph** [comment]
Since #57 is open and has the shared test suite we can close this.

**Pull request closed without merging**
