### PR TITLE
[DOCS] Clarify dot vs nested fields

### PR DESCRIPTION
**Pull request by lucabelluccini**
Explain how to avoid dots in field names.

### CODE REVIEW

**Comment by lucabelluccini** [comment]
Hello @karenzone - Would it be possible to review it?
I am not sure if the syntax is correct.
Feel free to amend my statement.

**Review by karenzone — COMMENTED** [review]
Docs build cleanly and render as expected.  Please give me a bit to validate content.

**Review by kares — APPROVED** [review]
:+1:

**Review by karenzone — APPROVED** [review]
Thanks for your contribution. LGTM

**Pull request merged**
