### PR TITLE
try to fix why jarvis can't publish this plugin

### PR DESCRIPTION
**Pull request by guyboertje**
Always gives sadpanda in the publish task.
```
(sadpanda) An error occurred in publish: Jarvis::SubprocessFailure - subprocess failed with code 1
```
Attempt 1

### CODE REVIEW

**Comment by ph** [comment]
@guyboertje Not sure how this solve jarvis, I would need a bit more details :)

**Comment by guyboertje** [comment]
from `gem_publisher-1.5.0/lib/gem_publisher/publisher.rb:L17`
```
@version = eval(File.read(gemspec), TOPLEVEL_BINDING).version.to_s
```
I don't think the eval finds the `VERSION` file. I could mess around trying to make it findable but I think I will do that for a later PR.

**Comment by ph** [comment]
@guyboertje Oh yes, I think that could be it.

**Comment by ph** [comment]
@guyboertje sorry, Just got a flash, but the _logstash-input-beats_ uses a similar gemfile and we were able to succesfully publish it with Jarvis, I am not sure what would be different from this one.

**Comment by guyboertje** [comment]
@ph Thinking back, the beats input is where I stole that line from.
I think I will merge, publish and circle back.

**Pull request merged**
